import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { newClient } from '../lib/contentful';
import { IPage, IPageSectionDefault } from '../@types/contentful_gen';

export const getStaticProps: GetStaticProps = async (context) => {
  const client = newClient();
  const entry = await client.getEntry<any>('4ktYp0QYgeCFD5SEqbqHoH');
  return {
    props: {
      entry,
    },
  };
};

type HomeProps = {
  entry: IPage;
};

const Home: NextPage<HomeProps> = ({ entry }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{entry.fields.title}</h1>

        <div>
          {entry.fields.sections?.map((s: IPageSectionDefault) => (
            <a key={s.fields.slug} href="#" className="">
              <h2>{s.fields.title}</h2>
              <p>{s.fields.content}</p>
            </a>
          ))}
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
